### ISSUE TITLE
SCRAM-SHA-256

### ISSUE THREAD

**Issue by Neustradamus** [johnyannj/cassandra-secure-plugin#2]
Dear @johnyannj,

Can you change SCRAM-SHA256 to SCRAM-SHA-256 (description at right too):
- https://github.com/johnyannj/cassandra-secure-plugin/search?q=SCRAM-SHA256

Can you remove the bad topic and add scram-sha-256 topic?

There is a "-" missing.

Thanks in advance.

**Comment by johnyannj** [comment]
ok

**Comment by Neustradamus** [comment]
@johnyannj: Thanks for your changes!

Do not forget, at right of this repository, the gear to change the last parts : topic and the description.

**Comment by Neustradamus** [comment]
@johnyannj: Thanks for your changes!

Do not forget, at right of this repository, the gear to change the last parts : topic and the description.

**Comment by Neustradamus** [comment]
@johnyannj: I wish you a Happy New Year 2022!

Can you change the bad scram-sha256 topic to scram-sha-256?

Currently there is a problem when people search ;)

Thanks in advance.

**Comment by Neustradamus** [comment]
@johnyannj: Can you change the bad scram-sha256 topic to scram-sha-256?

Currently there is a problem when people search ;)

At right, the gear...
